### ISSUE TITLE
Add target device layout benchmarks

### ISSUE THREAD

**Issue by bachase** [unitaryfoundation/ucc-bench#77]
Some passes, including those proposed as part of unitary hack 2025, work to improve routing/layout strategies when compiling to a specific physical device. We should add a set of benchmarks using the existing circuits, targeting some specific device layouts. We will do the best we can to make this work across compilers in the benchmark suite, but as a first step, can always restrict to ones that "easily" work with the qiskit backend mappings.

**Comment by bachase** [comment]
Simplifying assumptions for this initial task:

1. Only add benchmark ucc/qiskit compilers so we can use the standard IBM (fake) backends.
2. Do not add to automated runs (consider this separately)
3. Slightly leaning towards Option A below for specifying these. It's more concise, but assumes you'd typically want to benchmark the same set of circuits compiled for a set of backends. 


How to specify this?

#### Option A - Once per suite
```toml

# --------- Compilers ----------
# For now, restricting qiskit derived compilers to work with the same target-device options
[[compilers]]
id = "ucc"
[[compilers]]
id = "qiskit-default"


# --------- Target Devices ----------
[[target_devices]]
id = "FakeCairoV2"

[[target_devices]]
id = "FakeWashingtonV2"

[[target_devices]]
id = "FakeBrooklynV2"

# --------- Benchmarks ----------
[[benchmarks]]
id = "qaoa"
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
qasm_file = "circuits/benchpress/qaoa_barabasi_albert_N10_3reps_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id = "qv"
description = "Quantum Volume"
qasm_file = "circuits/benchpress/qv_N010_12345_basis_rz_rx_ry_cx.qasm"
```

#### Option B - Once per benchmark in suite
```toml

# --------- Compilers ----------
# For now, restricting qiskit derived compilers to work with the same target-device options
[[compilers]]
id = "ucc"
[[compilers]]
id = "qiskit-default"

# --------- Benchmarks ----------
[[benchmarks]]
id = "qaoa_cairo"
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
qasm_file = "circuits/benchpress/qaoa_barabasi_albert_N10_3reps_basis_rz_rx_ry_cx.qasm"
target_device = "FakeCairoV2"


[[benchmarks]]
id = "qaoa_washington"
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
qasm_file = "circuits/benchpress/qaoa_barabasi_albert_N10_3reps_basis_rz_rx_ry_cx.qasm"
target_device = "FakeWashingtonV2"
....

```

Any thoughts on these @jordandsullivan and @Misty-W ?
